name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Verify change in main.tex and simplecv.sty
        uses: tj-actions/changed-files@v23.1
        run: |
          changed_files=$(git diff --name-only HEAD)
          if [[ "$changed_files" != *"main.tex"* && "$changed_files" != *"simplecv.sty"* ]]; then
            echo "No changes in main.tex or simplecv.sty"
            exit 1
          fi
          echo "Build will proceed"

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          output_dir: build

      - name: Rename PDF file
        run: |
          mv main.pdf resume.pdf

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build LaTeX document
          file_pattern: resume.pdf
